server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/c1eye_shop?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: mmj_MMJ_123

c1eye:
  security:
    jwt-key: mmjmmj123
    token-expired-in: 86400000